name: Fury CI

on:
  push:
    branches:
      - main
      - 'releases/**'
      - 'deploy/**'
      - 'test*'
    tags:
      - v*
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

jobs:
  java:
    name: Java CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ["8", "11", "17"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
      - name: Run CI with Maven
        run: ./ci/run_ci.sh java${{ matrix.java-version }}
  javascript:
    name: Javascript CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run CI with NodeJS
        run: ./ci/run_ci.sh javascript
  cpp:
    name: C++ CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install bazel
        run: ./ci/run_ci.sh install_bazel
      - name: Run C++ CI with Bazel
        run: ./ci/run_ci.sh cpp
  python:
    name: Python CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6.15, 3.9.16]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install bazel
        run: ./ci/run_ci.sh install_bazel
      - name: Run Python CI
        run: ./ci/run_ci.sh python_without_arrow
  Lint:
    name: Code Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Check code style
        run: ./ci/run_ci.sh format
